---
# tasks file for DEPLOY_ENV
# essai
# essai
    
- name: Build image
  docker_image:
    name: "{{ container_image }}"
    source: ../../Docker_Image/DockerFile
    state: build
    
- name: Create Docker container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ container_image }}"
    volumes:
      - /Users/macbookpro/Desktop/jenkins:/home
    ports:
      - "8090:{{ application_port}}"
    state: running
        
