FROM nimmis/java-centos
MAINTAINER maintainer_name "emmanuelassamoi65@gmail.com"

ARG JAR_FILE=Project.jar
ARG SCRIPT_RUN=entrypoint.sh
ARG CONT_PORT_PUBLISH=8090
ARG CONT_VOLUME=/var/lib/app-java/config-app

COPY ${JAR_FILE} /opt/app-java/lib/app.jar
COPY ${SCRIPT_RUN} /opt/app-java/bin/entrypoint.sh
VOLUME ${CONT_VOLUME}
EXPOSE ${CONT_PORT_PUBLISH}
ENTRYPOINT ["/bin/bash"]
CMD ["/opt/app-java/bin/entrypoint.sh"]


