---
# tasks file for BUILD_DOCKER_IMAGE
- name: Copy dockerfile
  template:
    src=Dockerfile.j2
    dest="{{ Dockerfile_template_dest }}"
    force=yes
- name: Copy entrypoint script sh
  template:
    src=entrypoint.sh.j2
    dest="{{ Entrypoint_template_dest }}"
    force=yes

- name: build docker image from docker file
  docker_image:
    build:
      path: "{{ dockerfile_path }}"
      dockerfile: "{{ dockerfile_name }}"
      pull: false
      rm: yes
    name: "{{ image_name }}"
    tag: "{{ tag }}"
    source: 'build'
  delegate_to: 172.20.10.2
