---
# tasks file for BUILD_DOCKER_IMAGE

- name: build docker image from docker file
  docker_image:
    build:
      dockerfile: present
      rm: yes
      path: "{{ dockerfile_path }}"
    name: "{{ image_name }}"
    tag: "{{ tag }}"
    source: build
