---
# tasks file for BUILD_DOCKER_IMAGE

- name: build docker image from docker file
  docker_image:
    build:
      path: "{{ dockerfile_path }}"
      dockerfile: Dockerfile
      pull: false
      rm: yes
    name: "{{ image_name }}"
    tag: "{{ tag }}"
    source: 'build'
